prendre les coordonnées de chaque navire dans un array à 2 dimensions.
PA = 2 colonnes. int coordPorteAvions[5][2]

* menu principal
** fusionner menus 1 et 4

* placer les bateaux
** DONE tant qu'il y a un bateau
** DONE placer la proue et la poupe seulement pour aller plus vite
** DONE faire en sorte qu'en cas d'erreur de placement du bateau x, le programme boucle

placer le bateau :
while i < taille du bateau
placeBateau()
test range : 
** DONE dans le cadre ? 
** DONE en diagonale ? 
** DONE taille du bateau respectée ?
** DONE Non collé à un autre bateau ?
** effacer les poupes et proues des routine de vérification de bateaux collés
Ne chevauche pas un autre bateau ?
la proue ne s'efface pas car yProue décrémente dans la boucle. A faire en partie horizontale.

affiche le bateau placé
copie des coordonnées dans array tableauJoueurs[numeroJoueur].coordPorteAvions[5][2]
tableauJoueurs[numeroJoueur].coordPorteAvions[5][2] = {
{65 , 2}
{66 , 2}
{67 , 2}
{68 , 2}
{69 , 2}
}
/while

* tir
joueur 1 voit plateau "masque" qui ne contient que des tildes
tire [y][x] (reprendre placeBateau)
loop dans tous les arrays contenant les coordonnées des bateaux
si match
affiche X dans le plateau maitre de l'adversaire à la place du = 
La case correspondante du plateau masque = la case du plateau maitre.
retranche 1 point de vie au bateau concerné
sinon
affiche O dans le plateau masque du joueur
